# Exemplo de código para ler dados de um arquivo

Este script mostra um exemplo de como ler um arquivo de texto. Para tanto, utilizou-se um arquivo exemplo denominado `primeiras-linhas-eigen-6c4.gfc`. Este arquivo contém as primeiras linhas do arquivo `eigen-6c4.gfc`, que contem os coeficientes do modelo global do campo de gravidade **EIGEN-6C4** (Förste et al., 2014). O arquivo `eigen-6c4.gfc` completo pode ser baixado no site do IGCEM, na página [Table of models](http://icgem.gfz-potsdam.de/ICGEM/modelstab.html).

* Förste C., Bruinsma S.L., Abrikosov O., Lemoine J.-M., Schaller T., Götze H.-J., Ebbing J., Marty J.C., Flechtner F., Balmino G., Biancale R., 2014, EIGEN-6C4 The latest combined global gravity field model including GOCE data up to degree and order 2190 of GFZ Potsdam and GRGS Toulouse, 5th GOCE User Workshop, Paris, 25-28 November 2014

In [1]:
import numpy as np

## Leitura do arquivo pela função [`loadtxt`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html)

### Arquivo original

In [2]:
arquivo = open('primeiras-linhas-eigen-6c4.gfc', 'r')

print arquivo.read()

arquivo.close()

The Gravity Field Model EIGEN-6C4
-------------------------------------------------------------------------------------

EIGEN-6C4 is a static global combined gravity field modelup to degree and order 2190. 
It has been elaborated jointly  by GFZ Potsdam and GRGS Toulouse and contains the 
following  satellite and ground data:

- LAGEOS (deg. 2 - 30): 1985 - 2010

- GRACE RL03 GRGS (deg. 2 - 130): ten years 2003 - 2012

- GOCE-SGG data, processed by the direct approach (Pail et al. 2011,
  Bruinsma et al. 2014, to deg. 235) incl. the gravity gradient
  components Txx, Tyy, Tzz and Txz out of the following time spans:
  837 days out of the nominal mission time span 20091101 - 20120801
  422 days out of the lower orbit phase between 20120901 - 20130524
  The GOCE polar gaps were stabilized by the Spherical Cap Regularization
  (Metzler and Pail 2005) using the combined gravity field model EIGEN-6C3stat
  
- Terrestrial data (max degree 370):
  DTU12 ocean geoid data (Anderson et al. 2009

### Alternativa 1

Esta alternativa não especifica o formato dos dados, isto é, não especifica o parâmetro [`dtype`](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) dos dados a serem lidos no arquivo de texto.

In [3]:
dados1 = np.loadtxt('primeiras-linhas-eigen-6c4.gfc', skiprows=79, usecols=(1,2,3,4))

In [4]:
print dados1.dtype

float64


In [5]:
print dados1[:10]

[[  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00  -4.84165217e-04   0.00000000e+00]
 [  3.00000000e+00   0.00000000e+00   9.57173593e-07   0.00000000e+00]
 [  4.00000000e+00   0.00000000e+00   5.39998755e-07   0.00000000e+00]
 [  5.00000000e+00   0.00000000e+00   6.86465404e-08   0.00000000e+00]
 [  6.00000000e+00   0.00000000e+00  -1.49975581e-07   0.00000000e+00]
 [  7.00000000e+00   0.00000000e+00   9.04993978e-08   0.00000000e+00]
 [  8.00000000e+00   0.00000000e+00   4.94771153e-08   0.00000000e+00]
 [  9.00000000e+00   0.00000000e+00   2.80189081e-08   0.00000000e+00]]


Observe que todos os dados, inclusive as duas primeiras coluna de inteiros, foram transformados para `float`.

In [6]:
print dados1[:10,2]

[  1.00000000e+00   0.00000000e+00  -4.84165217e-04   9.57173593e-07
   5.39998755e-07   6.86465404e-08  -1.49975581e-07   9.04993978e-08
   4.94771153e-08   2.80189081e-08]


In [7]:
for i, linha in enumerate(dados1[:10]):
    print i, linha

0 [ 0.  0.  1.  0.]
1 [ 1.  0.  0.  0.]
2 [  2.00000000e+00   0.00000000e+00  -4.84165217e-04   0.00000000e+00]
3 [  3.00000000e+00   0.00000000e+00   9.57173593e-07   0.00000000e+00]
4 [  4.00000000e+00   0.00000000e+00   5.39998755e-07   0.00000000e+00]
5 [  5.00000000e+00   0.00000000e+00   6.86465404e-08   0.00000000e+00]
6 [  6.00000000e+00   0.00000000e+00  -1.49975581e-07   0.00000000e+00]
7 [  7.00000000e+00   0.00000000e+00   9.04993978e-08   0.00000000e+00]
8 [  8.00000000e+00   0.00000000e+00   4.94771153e-08   0.00000000e+00]
9 [  9.00000000e+00   0.00000000e+00   2.80189081e-08   0.00000000e+00]


In [8]:
for i, linha in enumerate(dados1[:10]):
    print i, linha[2]

0 1.0
1 0.0
2 -0.000484165217061
3 9.57173592933e-07
4 5.39998754738e-07
5 6.86465403533e-08
6 -1.49975580611e-07
7 9.04993977725e-08
8 4.94771152555e-08
9 2.80189081183e-08


In [9]:
for i, linha in enumerate(dados1[:10]):
    print i, linha[3]

0 0.0
1 0.0
2 0.0
3 0.0
4 0.0
5 0.0
6 0.0
7 0.0
8 0.0
9 0.0


In [10]:
print dados1[4]

[  4.00000000e+00   0.00000000e+00   5.39998755e-07   0.00000000e+00]


In [11]:
print dados1[4][0]

4.0


In [12]:
print dados1[4][2]

5.39998754738e-07


### Alternativa 2

Esta alternativa especifica o parâmetros [`dtype`](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) dos dados para cada coluna.

In [13]:
tipos = {'names': ('n', 'm', 'Anm', 'Bnm'), 'formats': ('int', 'int', 'double', 'double')}

dados2 = np.loadtxt('primeiras-linhas-eigen-6c4.gfc', dtype=tipos, skiprows=79, usecols=(1,2,3,4))

In [14]:
print dados2.dtype

[('n', '<i4'), ('m', '<i4'), ('Anm', '<f8'), ('Bnm', '<f8')]


In [15]:
print dados2[:10]

[(0, 0, 1.0, 0.0) (1, 0, 0.0, 0.0) (2, 0, -0.000484165217061, 0.0)
 (3, 0, 9.57173592933e-07, 0.0) (4, 0, 5.39998754738e-07, 0.0)
 (5, 0, 6.86465403533e-08, 0.0) (6, 0, -1.49975580611e-07, 0.0)
 (7, 0, 9.04993977725e-08, 0.0) (8, 0, 4.94771152555e-08, 0.0)
 (9, 0, 2.80189081183e-08, 0.0)]


Observe que os dados das duas primeiras colunas não foram convertidos para `float`.

In [16]:
print dados2[:10,2]

IndexError: too many indices for array

In [19]:
for i, linha in enumerate(dados2[:10]):
    print i, linha

0 (0, 0, 1.0, 0.0)
1 (1, 0, 0.0, 0.0)
2 (2, 0, -0.000484165217061, 0.0)
3 (3, 0, 9.57173592933e-07, 0.0)
4 (4, 0, 5.39998754738e-07, 0.0)
5 (5, 0, 6.86465403533e-08, 0.0)
6 (6, 0, -1.49975580611e-07, 0.0)
7 (7, 0, 9.04993977725e-08, 0.0)
8 (8, 0, 4.94771152555e-08, 0.0)
9 (9, 0, 2.80189081183e-08, 0.0)


In [20]:
for i, linha in enumerate(dados2[:10]):
    print i, linha[2]

0 1.0
1 0.0
2 -0.000484165217061
3 9.57173592933e-07
4 5.39998754738e-07
5 6.86465403533e-08
6 -1.49975580611e-07
7 9.04993977725e-08
8 4.94771152555e-08
9 2.80189081183e-08


In [21]:
for i, linha in enumerate(dados2[:10]):
    print i, linha[3]

0 0.0
1 0.0
2 0.0
3 0.0
4 0.0
5 0.0
6 0.0
7 0.0
8 0.0
9 0.0


In [22]:
print dados2[4]

(4, 0, 5.39998754738e-07, 0.0)


In [23]:
print dados2[4][0]

4


In [24]:
print dados2[4][2]

5.39998754738e-07
