# Exemplo de código para ler dados de um arquivo

Este script mostra um exemplo de como ler um arquivo de texto. Para tanto, utilizou-se um arquivo exemplo denominado `primeiras-linhas-eigen-6c4.gfc`. Este arquivo contém as primeiras linhas do arquivo `eigen-6c4.gfc`, que contem os coeficientes do modelo global do campo de gravidade **EIGEN-6C4** (Förste et al., 2014). O arquivo `eigen-6c4.gfc` completo pode ser baixado no site do IGCEM, na página [Table of models](http://icgem.gfz-potsdam.de/ICGEM/modelstab.html).

* Förste C., Bruinsma S.L., Abrikosov O., Lemoine J.-M., Schaller T., Götze H.-J., Ebbing J., Marty J.C., Flechtner F., Balmino G., Biancale R., 2014, EIGEN-6C4 The latest combined global gravity field model including GOCE data up to degree and order 2190 of GFZ Potsdam and GRGS Toulouse, 5th GOCE User Workshop, Paris, 25-28 November 2014

In [1]:
import numpy as np

## Leitura do arquivo pela função [`loadtxt`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html)

### Alternativa 1

In [2]:
dados1 = np.loadtxt('primeiras-linhas-eigen-6c4.gfc', skiprows=79, usecols=(1,2,3,4))

In [3]:
print dados1.dtype

float64


In [4]:
print dados1[:5]

[[  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00  -4.84165217e-04   0.00000000e+00]
 [  3.00000000e+00   0.00000000e+00   9.57173593e-07   0.00000000e+00]
 [  4.00000000e+00   0.00000000e+00   5.39998755e-07   0.00000000e+00]]


In [5]:
print dados1[:5,2]

[  1.00000000e+00   0.00000000e+00  -4.84165217e-04   9.57173593e-07
   5.39998755e-07]


In [6]:
for i, linha in enumerate(dados1[:5]):
    print i, linha

0 [ 0.  0.  1.  0.]
1 [ 1.  0.  0.  0.]
2 [  2.00000000e+00   0.00000000e+00  -4.84165217e-04   0.00000000e+00]
3 [  3.00000000e+00   0.00000000e+00   9.57173593e-07   0.00000000e+00]
4 [  4.00000000e+00   0.00000000e+00   5.39998755e-07   0.00000000e+00]


In [7]:
for i, linha in enumerate(dados1[:5]):
    print i, linha[2]

0 1.0
1 0.0
2 -0.000484165217061
3 9.57173592933e-07
4 5.39998754738e-07


In [8]:
for i, linha in enumerate(dados1[:5]):
    print i, linha[3]

0 0.0
1 0.0
2 0.0
3 0.0
4 0.0


In [9]:
print dados1[4]

[  4.00000000e+00   0.00000000e+00   5.39998755e-07   0.00000000e+00]


In [10]:
print dados1[4][0]

4.0


In [11]:
print dados1[4][2]

5.39998754738e-07


### Alternativa 2

In [12]:
tipos = {'names': ('n', 'm', 'Anm', 'Bnm'), 'formats': ('int', 'int', 'float', 'float')}

dados2 = np.loadtxt('primeiras-linhas-eigen-6c4.gfc', dtype=tipos, skiprows=79, usecols=(1,2,3,4))

In [13]:
print dados2.dtype

[('n', '<i4'), ('m', '<i4'), ('Anm', '<f8'), ('Bnm', '<f8')]


In [14]:
print dados2[:5]

[(0, 0, 1.0, 0.0) (1, 0, 0.0, 0.0) (2, 0, -0.000484165217061, 0.0)
 (3, 0, 9.57173592933e-07, 0.0) (4, 0, 5.39998754738e-07, 0.0)]


In [15]:
print dados2[:5,2]

IndexError: too many indices for array

In [16]:
for i, linha in enumerate(dados2[:5]):
    print i, linha

0 (0, 0, 1.0, 0.0)
1 (1, 0, 0.0, 0.0)
2 (2, 0, -0.000484165217061, 0.0)
3 (3, 0, 9.57173592933e-07, 0.0)
4 (4, 0, 5.39998754738e-07, 0.0)


In [17]:
for i, linha in enumerate(dados2[:5]):
    print i, linha[2]

0 1.0
1 0.0
2 -0.000484165217061
3 9.57173592933e-07
4 5.39998754738e-07


In [18]:
for i, linha in enumerate(dados2[:5]):
    print i, linha[3]

0 0.0
1 0.0
2 0.0
3 0.0
4 0.0


In [19]:
print dados2[4]

(4, 0, 5.39998754738e-07, 0.0)


In [20]:
print dados2[4][0]

4


In [21]:
print dados2[4][2]

5.39998754738e-07
